[server]
ip = "127.0.0.1"
port = ":3000"
version = "latest"
name = "sim"
debug = true
mode = "debug"
jwtKey="xxxxxx"
[extensions]
[extensions.mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
db = "sim"
[extension.redis]
host = "127.0.0.1"
port = 6379
db = 0
[qiniu]
acessKey="xxx"
secretKey="xxx"
bucket="sim"
qiniuServer="xxx"

